### PR TITLE
Feather nrf52832

### PR DESCRIPTION
**Pull request by outlandnish**
Works with Adafruit BSP 0.9.3 (the latest)

`platformio.ini`
```
[env:nrf52]
platform = https://github.com/nsamala/platform-nordicnrf52.git#feather_nrf52832
board = adafruit_feather_nrf52832
framework = arduino
upload_protocol = nrfutil
build_flags = 
  -DARDUINO_BSP_VERSION=\"0.9.2\"
```

Works alongside normal nRF boards so you should have trouble using those either.

It should be fairly trivial to add nRF52840 support now that this is available.

### CODE REVIEW

**Comment by jeremypoulter** [comment]
I have had a look through the changes, I am not going to pull them in right now as although it is nicer in terms of the implementation of the Arduino builder, having the Sandeep and Adafruit code split with some shared stuff this stops one important (at least to me) use case. The project I am working on currently builds with either the Sandeep core or the Adafruit core. there really is nothing inherent in the hardware that stops you from using whichever core you prefer as long as you have an appropriate variant for that board (which we do). So in that respect the previous implementation of adding the arduino-adafruit as a framework worked well.

I also have a bunch of other changes that conflict with the ones you have. Would you be able to rebase against the `adafruit_nrf52_feather_intergration_2` branch? 

Note: There are a bunch of changes in the `adafruit_nrf52_feather_intergration_2` branch for supporting the Sandeep and Adafruit cores in parallel as well, as well as J-Link support.

**Comment by jeremypoulter** [comment]
PS feel free to add comments to platformio/platform-nordicnrf52#23 if you don't agree with any of the changes I have made

**Comment by outlandnish** [comment]
I think that's a fair criticism. It may be worth adding a build flag like `USE_ADAFRUIT_BSP` or use `USE_SANDEEP_BSP` to explicitly tell the builder to use one BSP vs the other. That way you still get the flexibility to use whichever BSP but it's considered the `Arduino` framework. When you add it as a different framework, you suddenly lose PlatformIO's default checking to ensure libraries match the framework you're building against.

Thoughts on that?

**Comment by outlandnish** [comment]
I've done the rebase against your code. The only part I couldn't get working was the ARDUINO_BSP_VERSION so that's back to a build flag in the environment

**Comment by jeremypoulter** [comment]
Thanks, I think that will work, note it is the `adafruit_nrf52_feather_intergration_2` not `develop` branch that needs merging in. I have some other changes on `develop` that are not related.

**Comment by outlandnish** [comment]
That integration branch is the one I merged in

**Pull request merged**
